name: AutoRClone Sync 3
on:
  workflow_dispatch:
  schedule:
    - cron:  '30 7 * * *'
jobs:
  run-sync-service:
    runs-on: ubuntu-latest
    steps:
      - name: Install RClone
        run: |
          curl https://rclone.org/install.sh | sudo bash
      - name: Checkout repository code
        uses: actions/checkout@v2
      - name: Cd Into Repo
        run: |
          cd ${{ github.workspace }}
      - name: Install Requirements
        run: |
          pip3 install -r requirements.txt
      - name: Downloading config file
        run: |
          wget -qq ${{ secrets.CONF_URL }} -O rclone.conf
      - name: Downloading SA Accounts Zip (optional)
        env:
          SA_ZIP: ${{ secrets.SA_ZIP }}
        if: "${{ env.SA_ZIP != '' }}"
        run: |
           sudo wget -qq ${{ secrets.SA_ZIP }} -O accounts.zip
           sudo unzip -qq accounts.zip
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Start sync
        run: |
          sudo python3 rclone_sa_magic.py -s ${{ secrets.SRC2 }} -d ${{ secrets.DEST3 }} -dp Backup -b 1 -e 600
