name: GitHub Actions Demo
on: [ push ]
jobs:
  run-sync-service:
    runs-on: ubuntu-latest
    steps:
      - name: Install RClone
        run: |
          - curl https://rclone.org/install.sh | sudo bash
      - name: Downloading config file
        run: |
          wget ${{ secrets.CONF_URL }} -O rclone.config
      - name: Start sync
        run: |
          python3 sync.py
