name: GitHub Actions Demo
on: [ push ]
jobs:
  run-sync-service:
    runs-on: ubuntu-latest
    steps:
      - name: Install RClone
        run: |
          curl https://rclone.org/install.sh | sudo bash
          rclone help
      - name: Checkout repository code
        uses: actions/checkout@v2
      - name: Downloading config file
        run: |
          wget ${{ secrets.CONF_URL }} -O rclone.config
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
#      - name: Start sync
#        run: |
#          python3 sync.py
